### ISSUE TITLE
Default read timeout is too short for large registries 

### ISSUE THREAD

**Issue by eanmclaughlin** [ExidCuter/DockerRegistryV2Wrapper#1]
OkHttp's default read timeout is 10 seconds (https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/read-timeout/). This is too short to be able to retrieve the catalog of very large docker repositories. I suggest increasing the timeout and making it configurable by users of the library (ie your docker registry explorer plugin).

**Comment by ExidCuter** [comment]
Noted. Added a `timeout` parameter to the [DockerRegistry constructor](https://github.com/ExidCuter/DockerRegistryV2Wrapper/blob/master/src/main/java/org/tdfl/docker/DockerRegistry.java#L48).
